# pipe/task_push.py
# creates and updates github issues as task tracker per account
# one issue per account — tracks v1_done → v2_done status

import os
import json
import requests
from pipe.utils import get_lgr

lgr = get_lgr("task_push")

GH_API  = "https://api.github.com"


# ── github client ─────────────────────────────────────────
def _gh_hdrs() -> dict:
    token = os.getenv("GH_TOKEN")
    if not token:
        raise EnvironmentError("GH_TOKEN not set in cfg/.env")
    return {
        "Authorization": f"Bearer {token}",
        "Accept"       : "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28"
    }

def _repo() -> str:
    repo = os.getenv("GH_REPO")
    if not repo:
        raise EnvironmentError("GH_REPO not set in cfg/.env")
    return repo


# ── find existing issue ───────────────────────────────────
def _find_issue(acct_id: str) -> dict | None:
    """
    searches open + closed issues for one matching acct_id
    returns issue dict or None
    """
    repo = _repo()
    url  = f"{GH_API}/repos/{repo}/issues"

    for state in ["open", "closed"]:
        resp = requests.get(
            url,
            headers=_gh_hdrs(),
            params={"state": state, "per_page": 50}
        )
        if resp.status_code != 200:
            lgr.warning(f"gh issues list failed: {resp.status_code}")
            return None

        for issue in resp.json():
            if acct_id in issue.get("title", ""):
                return issue

    return None


# ── build issue body ──────────────────────────────────────
def _build_body(memo: dict, status: str, changelog: dict | None = None) -> str:
    """
    builds markdown body for github issue
    """
    co      = memo.get("co_name") or "Unknown"
    tz      = memo.get("timezone") or "Not specified"
    open_qs = memo.get("open_qs", [])

    # biz hours summary
    biz = memo.get("biz_hrs", {})
    active_days = [
        d.capitalize() for d, v in biz.items()
        if v.get("active")
    ]
    hrs_str = f"{', '.join(active_days)}" if active_days else "Not specified"

    # open questions block
    qs_block = "\n".join(f"- {q}" for q in open_qs) if open_qs else "None remaining"

    # changelog block
    cl_block = ""
    if changelog:
        changes = changelog.get("changes", [])
        cl_block = f"""
## Changelog (v1 → v2)
- Total changes: {changelog.get('total_changes', 0)}
"""
        for c in changes[:10]:  # cap at 10
            cl_block += f"- [{c['action']}] `{c['field']}`\n"

    return f"""
## Account: {co}
**Account ID:** `{memo['acct_id']}`
**Status:** `{status}`
**Memo Version:** `{memo.get('memo_ver', 'unknown')}`
**Timezone:** {tz}
**Business Days:** {hrs_str}

## Emergency Triggers
{chr(10).join(f'- {t}' for t in memo.get('emrg_triggers', [])) or 'Not specified'}

## Emergency Routing
- Primary: {memo.get('emrg_routing', {}).get('primary_name')} — {memo.get('emrg_routing', {}).get('primary_ph')}
- Secondary: {memo.get('emrg_routing', {}).get('secondary_name')} — {memo.get('emrg_routing', {}).get('secondary_ph')}

## Open Questions ({len(open_qs)} remaining)
{qs_block}
{cl_block}
---
*Auto-generated by Clara Agent Ops Pipeline*
""".strip()


# ── create issue ──────────────────────────────────────────
def _create_issue(acct_id: str, co_name: str, body: str) -> dict:
    repo  = _repo()
    url   = f"{GH_API}/repos/{repo}/issues"
    title = f"[Clara] {co_name or acct_id} — {acct_id}"

    resp = requests.post(
        url,
        headers=_gh_hdrs(),
        json={
            "title" : title,
            "body"  : body,
            "labels": ["clara-onboarding"]
        }
    )

    if resp.status_code == 422:
        # label might not exist — retry without label
        resp = requests.post(
            url,
            headers=_gh_hdrs(),
            json={"title": title, "body": body}
        )

    if resp.status_code not in (200, 201):
        raise RuntimeError(f"gh create issue failed: {resp.status_code} {resp.text}")

    return resp.json()


# ── update issue ──────────────────────────────────────────
def _update_issue(issue_num: int, body: str, status: str) -> dict:
    repo  = _repo()
    url   = f"{GH_API}/repos/{repo}/issues/{issue_num}"

    # close issue if v2_done
    state = "closed" if status == "v2_done" else "open"

    resp = requests.patch(
        url,
        headers=_gh_hdrs(),
        json={"body": body, "state": state}
    )

    if resp.status_code not in (200, 201):
        raise RuntimeError(f"gh update issue failed: {resp.status_code} {resp.text}")

    return resp.json()


# ── main push fn ──────────────────────────────────────────
def push_task(
    memo     : dict,
    status   : str,
    changelog: dict | None = None
) -> dict:
    """
    creates or updates a github issue for this account

    args:
        memo      → account memo dict
        status    → 'v1_done' or 'v2_done'
        changelog → changelog dict (pipeline B only)

    returns:
        issue dict with number and url
    """
    acct_id = memo["acct_id"]
    co_name = memo.get("co_name") or acct_id

    lgr.info(f"pushing task | {acct_id} | status: {status}")

    body          = _build_body(memo, status, changelog)
    existing      = _find_issue(acct_id)

    if existing:
        issue = _update_issue(existing["number"], body, status)
        lgr.info(f"issue updated → #{issue['number']} | {issue['html_url']}")
    else:
        issue = _create_issue(acct_id, co_name, body)
        lgr.info(f"issue created → #{issue['number']} | {issue['html_url']}")

    return {
        "issue_num" : issue["number"],
        "issue_url" : issue["html_url"],
        "status"    : status
    }